apiVersion: batch/v1
kind: Job
metadata:
  name: mx-scheduler
spec:
  template:
    metadata:
      name: mx-scheduler
      labels:
        app: mx-scheduler
    spec:
      containers:
      - name: mx-scheduler
        image: gcr.io/agwlkubeflow/mxnet
        imagePullPolicy: IfNotPresent
        command: ["python", "/mxnet/example/image-classification/train_mnist.py", "--kv-store=dist_async", "--num-epochs=1"]
        env:
        - name: DMLC_PS_ROOT_URI
          value: "mx-scheduler"
        - name: DMLC_PS_ROOT_PORT
          value: "9091"
        - name: DMLC_NUM_WORKER
          value: "3"
        - name: DMLC_NUM_SERVER
          value: "3"
        - name: PS_VERBOSE
          value: "2"
        - name: DMLC_USE_KUBERNETES
          value: "1"
        - name: DMLC_ROLE
          value: "scheduler"
      restartPolicy: OnFailure
---
apiVersion: v1
kind: Service
metadata:
  name: mx-scheduler
spec:
  selector:
    app: mx-scheduler
  ports:
  - protocol: TCP
    port: 9091
    targetPort: 9091
---
apiVersion: batch/v1
kind: Job
metadata:
  name: mx-server
spec:
  parallelism: 3
  completions: 3
  template:
    metadata:
      name: mx-server
      labels:
        app: mx-server
    spec:
      containers:
      - name: mx-server
        image: gcr.io/agwlkubeflow/mxnet
        imagePullPolicy: IfNotPresent
        command: ["python", "/mxnet/example/image-classification/train_mnist.py", "--kv-store=dist_async", "--num-epochs=1"]
        env:
        - name: DMLC_PS_ROOT_URI
          value: "mx-scheduler"
        - name: DMLC_PS_ROOT_PORT
          value: "9091"
        - name: DMLC_NUM_WORKER
          value: "3"
        - name: DMLC_NUM_SERVER
          value: "3"
        - name: PS_VERBOSE
          value: "2"
        - name: DMLC_USE_KUBERNETES
          value: "1"
        - name: DMLC_ROLE
          value: "server"
      restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: Job
metadata:
  name: mx-worker
spec:
  parallelism: 3
  completions: 3
  template:
    metadata:
      name: mx-worker
      labels:
        app: mx-worker
    spec:
      containers:
      - name: mx-worker
        image: gcr.io/agwlkubeflow/mxnet
        imagePullPolicy: IfNotPresent
        command: ["python", "/mxnet/example/image-classification/train_mnist.py", "--kv-store=dist_async", "--num-epochs=1"]
        env:
        - name: DMLC_PS_ROOT_URI
          value: "mx-scheduler"
        - name: DMLC_PS_ROOT_PORT
          value: "9091"
        - name: DMLC_NUM_WORKER
          value: "3"
        - name: DMLC_NUM_SERVER
          value: "3"
        - name: PS_VERBOSE
          value: "2"
        - name: DMLC_USE_KUBERNETES
          value: "1"
        - name: DMLC_ROLE
          value: "worker"
      restartPolicy: OnFailure
